#!/bin/sh
# Displays the current time in HH:MM:SS (AM|PM)

case $BLOCK_BUTTON in
    1) "$TERMINAL" -e calcurse ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

echo "^c#f6c177^󱑆 $(date '+%I:%M:%S %p')"
