#!/bin/sh

lpulsemixer() {
	"$TERMINAL" -e pulsemixer
	kill -42 $(pidof dwmblocks)
}

case $BLOCK_BUTTON in
    1) lpulsemixer ;;
    2) pamixer -t ;;
    4) pamixer -i 3 ;;
    5) pamixer -d 3 ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

if [ "$(pamixer --get-mute)" = true ]; then
    echo " VOL MUT " 
    exit
fi

vol="$(pamixer --get-volume)"

echo " VOL $vol% "
